import 'package:flutter/material.dart';import 'package:oner_s_application1/core/app_export.dart';import 'package:oner_s_application1/widgets/app_bar/appbar_image_1.dart';import 'package:oner_s_application1/widgets/app_bar/appbar_subtitle_1.dart';import 'package:oner_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:oner_s_application1/widgets/custom_elevated_button.dart';import 'package:oner_s_application1/widgets/custom_outlined_button.dart';import 'package:oner_s_application1/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class K44Screen extends StatelessWidget {K44Screen({Key? key}) : super(key: key);

TextEditingController emailaddressController = TextEditingController();

TextEditingController passwordoneController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primary, resizeToAvoidBottomInset: false, appBar: CustomAppBar(leadingWidth: getHorizontalSize(48), leading: AppbarImage1(svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: getMargin(left: 24, top: 14, bottom: 17), onTap: () {onTapArrowleftone(context);}), centerTitle: true, title: AppbarSubtitle1(text: "登录")), body: Container(width: double.maxFinite, padding: getPadding(left: 24, top: 23, right: 24, bottom: 23), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Align(alignment: Alignment.centerLeft, child: Text("欢迎来到头条影视", style: theme.textTheme.titleLarge)), CustomTextFormField(controller: emailaddressController, margin: getMargin(top: 22), hintText: "邮箱地址", hintStyle: theme.textTheme.bodyMedium!, prefix: Container(margin: getMargin(left: 16, top: 14, right: 12, bottom: 14), child: CustomImageView(svgPath: ImageConstant.imgMail)), prefixConstraints: BoxConstraints(maxHeight: getVerticalSize(48))), CustomTextFormField(controller: passwordoneController, margin: getMargin(top: 16), hintText: "请输入密码", hintStyle: theme.textTheme.bodyMedium!, textInputAction: TextInputAction.done, prefix: Container(margin: getMargin(left: 16, top: 14, right: 12, bottom: 14), child: CustomImageView(svgPath: ImageConstant.imgLock)), prefixConstraints: BoxConstraints(maxHeight: getVerticalSize(48))), Align(alignment: Alignment.centerRight, child: Padding(padding: getPadding(top: 16, right: 28), child: Text("忘记密码?", style: CustomTextStyles.bodyMediumOnPrimaryContainer_1))), CustomElevatedButton(text: "登录", margin: getMargin(top: 14), buttonStyle: CustomButtonStyles.fillBlack, buttonTextStyle: CustomTextStyles.bodyLargeInterGray500), Padding(padding: getPadding(top: 18), child: Text("or", style: CustomTextStyles.bodyMediumGray70001)), CustomElevatedButton(text: "Apple帐号登录", margin: getMargin(top: 12), leftIcon: Container(margin: getMargin(right: 8), child: CustomImageView(svgPath: ImageConstant.imgEyePrimary)), buttonStyle: CustomButtonStyles.fillGrayTL4, buttonTextStyle: CustomTextStyles.bodyLargePrimary), CustomOutlinedButton(text: "Google帐号登录", margin: getMargin(top: 16), leftIcon: Container(margin: getMargin(right: 9), child: CustomImageView(svgPath: ImageConstant.imgTwitter))), Spacer(), Padding(padding: getPadding(bottom: 66), child: RichText(text: TextSpan(children: [TextSpan(text: "还没有帐号?", style: CustomTextStyles.bodyMediumOnPrimaryContainer), TextSpan(text: " "), TextSpan(text: "立即注册", style: CustomTextStyles.bodyMediumLightblueA700)]), textAlign: TextAlign.left))])))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowleftone(BuildContext context) { Navigator.pop(context); } 
 }
